// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID        int     `json:"id"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	Books     []*Book `json:"books"`
}

type Book struct {
	ID       int     `json:"id"`
	Title    *string `json:"title"`
	AuthorID int     `json:"authorId"`
	Author   *Author `json:"author"`
}

type NewAuthor struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type NewBook struct {
	Title    string `json:"title"`
	AuthorID int    `json:"authorId"`
}
